// images
export {default as FullLogo} from './images/full_logo.png'
export {default as Pos} from './images/pos.png'
export {default as Acc1} from './images/acc_1.png'
export {default as Acc2} from './images/acc_2.png'
export {default as Acc3} from './images/acc_3.png'
export {default as Img1} from './images/img1.jpeg'
export {default as Img2} from './images/img2.jpeg'
export {default as Img3} from './images/img3.jpeg'
export {default as Img4} from './images/img4.jpeg'
export {default as Img5} from './images/img5.jpeg'
export {default as Img6} from './images/img6.jpeg'
export {default as Img7} from './images/img7.jpeg'
export {default as Img8} from './images/img8.jpeg'
export {default as Img9} from './images/img9.png'
export {default as Img10} from './images/img10.png'
export {default as Img11} from './images/img11.jpeg'
export {default as Img12} from './images/img12.jpeg'
export {default as Img13} from './images/img13.jpeg'
export {default as Img14} from './images/img14.jpeg'
export {default as Img15} from './images/img15.jpeg'
export {default as Img16} from './images/img16.jpeg'

// svg
export {default as OurCompany} from './svg/our_company.svg'
export {default as ATMCard} from './svg/atm_card.svg'

// tsx
export {default as BgStyle} from './tsx/BgStyle'

// partners_logo
export {default as PsbLogo} from './partners_logo/9psb_logo.png'
export {default as AccessBankLogo} from './partners_logo/access_bank_logo.png'
export {default as EcoBankLogo} from './partners_logo/eco_bank_logo.png'
export {default as FCMBLogo} from './partners_logo/fcmb_logo.png'
export {default as FirstBankLogo} from './partners_logo/first_bank_logo.png'
export {default as GlobusBankLogo} from './partners_logo/globus_bank_logo.png'
export {default as GtbankLogo} from './partners_logo/gtbank_logo.png'
export {default as HeritageBankLogo} from './partners_logo/heritage_bank_logo.png'
export {default as StanbicBankLogo} from './partners_logo/stanbic_bank_logo.png'
export {default as SterlingBankLogo} from './partners_logo/sterling_bank_logo.png'
export {default as UBALogo} from './partners_logo/uba_logo.png'
export {default as WemaBankLogo} from './partners_logo/wema_bank_logo.png'
export {default as ZenithBankLogo} from './partners_logo/zenith_bank_logo.png'

// custom_icons
export {default as BuildingsIcon} from './custom_icons/buildings.svg'
export {default as PeopleIcon} from './custom_icons/people.svg'
export {default as FlashIcon} from './custom_icons/flash.svg'
export {default as GPSIcon} from './custom_icons/gps.svg'
export {default as CrownIcon} from './custom_icons/crown.svg'
export {default as AwardIcon} from './custom_icons/award.svg'
export {default as ProfileIcon} from './custom_icons/profile.svg'
export {default as PartnershipIcon} from './custom_icons/partnership.svg'
export {default as WalletIcon} from './custom_icons/wallet.svg'
export {default as DocumentUpload} from './custom_icons/document_upload.svg'

// backgrounds
export {default as MapBase} from './backgrounds/map_base.svg'
export {default as MapBase2} from './backgrounds/map_base2.svg'
export {default as LineBg } from './backgrounds/line_bg.svg'
export {default as Stripe} from './backgrounds/stripe.svg'
export {default as Circle} from './backgrounds/circle.svg'
export {default as VectorLine} from './backgrounds/vector_line.svg'
export {default as Objectives} from './backgrounds/objectives.svg'

